---
# tasks file for utils
- name: Installing vim,htop,git,pip3,openfortivpn and virtualenv on Ubuntu
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - python3-apt
    - openfortivpn
    - vim
    - tmux
    - htop
    - git
    - python3-pip
    - python3-virtualenv
  when: ansible_distribution == 'Ubuntu'

- name: Installing vim,htop,git,pip3,openfortivpn and virtualenv on Fedora
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - tmux
    - htop
    - git
    - python3-pip
    - python3-virtualenv
  when: ansible_distribution == 'Fedora'

- name: Installing vim,htop,git,pip3,openfortivpn and virtualenv on CentOS
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - tmux
    - htop
    - git
    - python3-pip
    - python3-virtualenv
  when: ansible_distribution == 'Centos'
  
