---
# tasks file for roles/teams
- name: Installing Microsoft Teams
  apt:
    deb: https://teams.microsoft.com/downloads/desktopurl?env=production&plat=linux&arch=x64&download=true&linuxArchiveType=deb
    state: present
  when: ansible_os_family == 'Debian'

- yum:
    name: https://teams.microsoft.com/downloads/desktopurl?env=production&plat=linux&arch=x64&download=true&linuxArchiveType=rpm
    state: present
  when: ansible_os_family == 'CentOS'