---
- name: Installing Docker
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_os_family == 'Debian'

- dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_distribution == 'Fedora'

- yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  when: ansible_distribution == 'Centos'
